### ISSUE TITLE
Using Widgets as an element in Layotter?

### ISSUE THREAD

**Issue by heyalbert** [hingst/layotter#5]
Is it possible to use normal wordpress widgets in Layotter? Like the wordpress vanilla widgets or any other widget I can normally put under a sidebar section.

**Comment by hingst** [comment]
Widgets are currently not supported because Layotter was designed around Advanced Custom Fields, and widgets are structured very differently. Making Layotter work with native widgets would require a lot of changes to very basic underlying concepts. I'll happily accept contributions making this possible, but honestly it's currently not something I'm planning to do myself.
